RETURN_SOURCE_DOCUMENTS = "True"
TOP_K = 1
CHUNK_SIZE = 2000
CHUNK_OVERLAP = 100
DATA_PATH = 'cook_book_data'
VECTOR_DB_PATH = 'vector_db'
MODEL_TYPE = 'llama'
MODEL_BIN_PATH = 'models/llama-2-7b-chat.ggmlv3.q8_0.bin' # download from: https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML
#MODEL_BIN_PATH = 'models/llama-2-13b-chat.ggmlv3.q8_0.bin' # download from: https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML
EMBEDDING_MODEL_NAME = 'sentence-transformers/all-MiniLM-L6-v2'
MAX_NEW_TOKENS = 512
CONTEXT_LENGTH = 3000
TEMPERATURE = 0.1
GPU_LAYERS = 32